import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";


export default function Home() {
  const { data } = useSession();
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
    <p>{data?.user?.email}</p>
    <p>{data?.user?.image}</p>
<Image src={data?.user?.image ?? ''} width={200} height={200} alt="" />
      </main>
    </>
  );
}
